// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGsXb4SblelKXU1x7nvIux3FbmS1Ve_Gc',
    appId: '1:1092645072600:web:f3ef200924a08b114cb1ad',
    messagingSenderId: '1092645072600',
    projectId: 'wemeet-3bf18',
    authDomain: 'wemeet-3bf18.firebaseapp.com',
    storageBucket: 'wemeet-3bf18.firebasestorage.app',
    measurementId: 'G-TF7ZBR402T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6RsF5W_Ai-5F_o9VyJtbl70j2KfREA5I',
    appId: '1:1092645072600:android:0c835645a4ebb6eb4cb1ad',
    messagingSenderId: '1092645072600',
    projectId: 'wemeet-3bf18',
    storageBucket: 'wemeet-3bf18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_iWRWYMRrQ58Oz-pc4yhfkkdTkquQ2uY',
    appId: '1:1092645072600:ios:b35fff0ec419e5e44cb1ad',
    messagingSenderId: '1092645072600',
    projectId: 'wemeet-3bf18',
    storageBucket: 'wemeet-3bf18.firebasestorage.app',
    iosBundleId: 'com.example.wemeet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_iWRWYMRrQ58Oz-pc4yhfkkdTkquQ2uY',
    appId: '1:1092645072600:ios:b35fff0ec419e5e44cb1ad',
    messagingSenderId: '1092645072600',
    projectId: 'wemeet-3bf18',
    storageBucket: 'wemeet-3bf18.firebasestorage.app',
    iosBundleId: 'com.example.wemeet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGsXb4SblelKXU1x7nvIux3FbmS1Ve_Gc',
    appId: '1:1092645072600:web:d118476a08eeb82f4cb1ad',
    messagingSenderId: '1092645072600',
    projectId: 'wemeet-3bf18',
    authDomain: 'wemeet-3bf18.firebaseapp.com',
    storageBucket: 'wemeet-3bf18.firebasestorage.app',
    measurementId: 'G-7FXH67MG4G',
  );
}
